# .github/workflows/update-age.yml
name: Update Age in README

on:
  schedule:
    # Run at 00:00 on the 1st of January every year
    - cron: '0 0 1 1 *'
  # Optional: Enable manual running from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update age in README
        run: |
          # Thay đổi 2004 bằng năm sinh
          BIRTH_YEAR=2004
          CURRENT_YEAR=$(date +%Y)
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))
          
          # Update the age in the README.md
          sed -i "s/I'm \*\*[0-9]\+\*\* and a Virgo/I'm \*\*$AGE\*\* and a Virgo/g" README.md
      
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'github-action@users.noreply.github.com'
          git add README.md
          git commit -m "Updating age automatically $(date +%Y)" || echo "No change"
          git push