# .github/workflows/update-age.yml
name: Update Age in README

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

# Thêm quyền để cho phép workflow ghi vào repository
permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update age in README
        run: |
          BIRTH_YEAR=2004
          CURRENT_YEAR=$(date +%Y)
          AGE=$((CURRENT_YEAR - BIRTH_YEAR))
          
          sed -i "s/I'm \*\*[0-9]\+\*\* and a Virgo/I'm \*\*$AGE\*\* and a Virgo/g" README.md
      
      - name: Commit changes
        run: |
          git config --global user.name 'xyan-dhgb'
          git config --global user.email 'giabaoctg@gmail.com'
          git add README.md
          git commit -m "Cập nhật tuổi tự động cho năm $(date +%Y)" || echo "Không có thay đổi"
          git push
